### ISSUE TITLE
Could this work with my own Team Foundation Server ?

### ISSUE THREAD

**Issue by rhadhy** [Microsoft/vsts-vscode#11]
I love work with vscode but i can connect with my own TFS, have any special configuration to work with this extension?

**Comment by jeffyoung** [comment]
Unfortunately, not at this time.  We are working through our plans on how to handle authentication with TFS (on-prem) across Windows, Mac and Linux.  Team Services and TFS (on-prem) support different authentication mechanisms and the initial release of the extension targeted Team Services (previously known as Visual Studio Online).  We do plan on supporting TFS (on-prem) but we need to figure out which mechanisms to use (and implement appropriately).

**Comment by rhadhy** [comment]
ok, thnks ill be waiting

**Comment by jeffyoung** [comment]
We just added support to the extension for Team Foundation Server 2015 Update 2 (and later).  The official announcement is [here](https://blogs.msdn.microsoft.com/visualstudioalm/2016/07/11/the-team-services-extension-for-visual-studio-code-now-supports-team-foundation-server-2015-update-2-and-later/).
