### ISSUE TITLE
Question: Will this work with VSTS and git-tfs?

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vsts-vscode#13]
Hello,

We use VSTS with tfs not git so I use git-tfs.  Does or will this plugin work in this scenario.  I understand that some pieces like pull requests wouldn't work but was curious about the other parts.

Thanks!

**Comment by jeffyoung** [comment]
Hi David.  I took a look at git-tfs and it appears that it "clones" a Git repository locally for syncing the code from/to TFS.  IOW, there isn't a remote for the Git repository on Team Services.  The VS Code extension uses the Git configuration to make calls to Team Services to do things like query work items and pull requests and to navigate to URLs with your web browser.  So it expects that the Git repository you're working in to be up on Team Services.  In the case of git-tfs, there doesn't appear to be a "remote repository" so I would expect that not much (if any) of the functionality of the extension would work.

**Comment by dawilliams** [comment]
Ok.  Thank you for your quick response Jeff.

David

On April 14, 2016 at 4:01:12 PM, Jeff Young (notifications@github.com) wrote:

Hi David. I took a look at git-tfs and it appears that it "clones" a Git repository locally for syncing the code from/to TFS. IOW, there isn't a remote for the Git repository on Team Services. The VS Code extension uses the Git configuration to make calls to Team Services to do things like query work items and pull requests and to navigate to URLs with your web browser. So it expects that the Git repository you're working in to be up on Team Services. In the case of git-tfs, there doesn't appear to be a "remote repository" so I would expect that not much (if any) of the functionality of the extension would work.
