### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/vsts-vscode#147]
I'm trying to figure out how to get started from scratch.  I tried the [YouTube ](https://www.youtube.com/watch?v=tpjj5i8f6BE)video but it starts with a VSTS repo.

How do I get started from a brand new project?

I know in Visual Studio I can create a new sln with a new repo and then publish that repo.  How do I go the same in VS code with VSTS?  Thanks!

**Comment by jeffyoung** [comment]
Hi @spottedmahn.  Thanks for the feedback and for trying out the extension.

The functionality you're looking for doesn't exist quite yet.  In upcoming sprints we're going to investigate to see if we can do exactly what you're asking for here.  Today, as you've noticed, the extension expects you to have a Team Services (or TFS) repository already cloned.  If you already have a team project created (and a default Git repository), you can push your local repository to that remote and the extension will detect that change and re-initialize (see those details at #27).  But, today, that's as close as we get to what you're looking for.
