### ISSUE TITLE
Signin doesn't work

### ISSUE THREAD

**Issue by Daniel-Esser** [Microsoft/vsts-vscode#160]
![image](https://cloud.githubusercontent.com/assets/7695350/24288800/0c57b9e2-107f-11e7-9bc0-a6b04f9c3135.png)

![image](https://cloud.githubusercontent.com/assets/7695350/24288835/24bd5b04-107f-11e7-9bff-f9af71f986a5.png)

**Comment by jpricketMSFT** [comment]
@Daniel-Esser - can you provide your vscode logs? That should provide more info on exactly what the error is. You can see how to turn on debug logging for the extension in the Readme.md or by going to the main page https://github.com/Microsoft/vsts-vscode 
thanks,
Jason
