### ISSUE TITLE
guid specified for parameter projectid must not be guid.empty

### ISSUE THREAD

**Issue by fromthewoods** [Microsoft/vsts-vscode#178]
Trying to use VScode instead of Visual Studio for my DevOps work since I'm mainly writing PowerShell. I have an existing folder inside a huge project shared by many people. I've configured 
    "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\TF.exe"
and I can connect to TFS but something still isn't working.

I can see my modified files in the Source Control panel once I switch SCM to TFVC, but the icons at the bottom of VScode aren't working.
![image](https://cloud.githubusercontent.com/assets/5445673/25052685/e521105a-2107-11e7-8458-08d13cff22c7.png)
When I click on the build icon, I get a popup window that says "Windows cannot find 'undefined/_build'. Make sure you typed the name correctly, and then try again."
![image](https://cloud.githubusercontent.com/assets/5445673/25052704/ffdcdfa0-2107-11e7-820e-751d9db184b7.png) 
when I click on the work item icon I get this message:
![image](https://cloud.githubusercontent.com/assets/5445673/25052757/5ff4e694-2108-11e7-812c-27ff65f46eec.png)
I'm sure my project needs to additional items, I'm just not sure what. Forgive me, I'm not a TFS/Visual Studio expert.

Windows 7
Visual Studio 2015 Update 3
TFS 2015 Update 3 (on prem)
VSCode 1.11.2

**Comment by jeffyoung** [comment]
On first glance, I was thinking that perhaps TFS prior to 2015 U2 was being used (as those errors are usually symptomatic of an earlier version of TFS).  With a bit closer inspection, it appears that we don't have the proper team project URL.  Ignoring those errors for a minute, can you successfully edit your files and get the expected results in the TFVC viewlet?

Also, would you be willing to [turn on logging](https://github.com/Microsoft/vsts-vscode#logging) and provide that information (you may want to remove some PII beforehand)?

**Comment by fromthewoods** [comment]
I can see see files in the Source Viewlet.
![image](https://cloud.githubusercontent.com/assets/5445673/25058768/fa182d0c-2131-11e7-9f0b-0fbcc6faa655.png)
Attached is the debug log.
[team-extension.1.log.txt](https://github.com/Microsoft/vsts-vscode/files/923135/team-extension.1.log.txt)

**Comment by jeffyoung** [comment]
Thanks for the screenshot and the log @fromthewoods.  The log was really helpful.

It looks like you're running into #175 since we can't determine the team project from the output of the `workfold` command.  That thread has some ideas about how we could address it (but it requires changes to the extension).

That said, can you describe your workspace mappings (how you typically work)?  My expectation is that most folks would map at least one team project root (but I'm finding out a bit differently).

**Comment by fromthewoods** [comment]
I'm no expert, but I believe I have one workspace and my "projects" are just folders under this huge shared workspace. Does that help?

**Comment by jeffyoung** [comment]
Yes.  That indicates that what you're seeing is the same as @175 (with the side-effect of what you're seeing in the status bar since we can't determine the team project).

**Comment by jeffyoung** [comment]
Merged PR should prevent these errors from displaying (although a message to that effect will be displayed in the status bar).  Other issues are tracked in #175.
