### ISSUE TITLE
Add a Changelog file to the repo to enable native Changelog view in VS Code

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vsts-vscode#183]
VS Code powers it's integrated Changelog view based on a `CHANGELOG.md` file, placed at the root of the project's folder. See https://code.visualstudio.com/docs/extensions/publish-extension#_marketplace-integration for details.

<img width="664" alt="screenshot 2017-04-20 23 11 14" src="https://cloud.githubusercontent.com/assets/406937/25252975/56190fda-261f-11e7-9d8c-2b9158faded2.png">

It would be great to add this to allow people to see what changed in a new version of this extension right from VS Code! 👍

**Comment by jeffyoung** [comment]
Good idea @lumaxis.

Maybe something generated with a tool like [github-changelog-generator](https://github.com/skywinder/github-changelog-generator).  Although it'd be great if it was something I could put right into my gulp build (via npm).

**Comment by lumaxis** [comment]
@jeffyoung How do you currently create the GitHub releases? Maybe working the other way around and auto-creating those from a Changelog file would be an easier solution. Maybe using something like https://github.com/MoOx/github-release-from-changelog?

**Comment by jeffyoung** [comment]
I currently do it manually.  I keep track of the "Release Notes" myself (since I don't want all of the commits showing up there (or in a CHANGELOG file)) and once I get the VSIX file ready to upload to the marketplace, I create the release in GitHub.  Since I have the vsix file ready, I can just drag-and-drop it right into the Release so it's available there (mostly for historical purposes).

**Comment by jeffyoung** [comment]
I went ahead and created this (although I'll have to do it manually for now).  Thanks for the suggestion @lumaxis.

**Comment by lumaxis** [comment]
Thank you 🙏

**Comment by lumaxis** [comment]
It's beautiful! 🙂 

<img width="786" alt="screenshot 2017-04-24 23 33 40" src="https://cloud.githubusercontent.com/assets/406937/25359735/8c4d849e-2946-11e7-8be3-66dc35aa0c53.png">
