### ISSUE TITLE
on premises TFS2015 Update 3 - Unauthorized. check your authentication credentials and try again.

### ISSUE THREAD

**Issue by Yaash19** [Microsoft/vsts-vscode#187]
Hello,
I am new to visual studio code and try to integrate with our TFS 2015

I have Visual studio code v 1.11.2 and Extn Visual Studio Team Services 1.11.7.0

Below is the settings i have, with it i don't see the "Team!"icon

![image](https://cloud.githubusercontent.com/assets/28021175/25404406/d2a17022-29cd-11e7-9f8a-79d504a9f735.png)

When i give my TFS credential i keep getting unauthorized, check your authentication. But i am giving the correct credentials. I was able to connect fine with same credentials with TFS using visual studio 2015

Below is the log 
[team-extension1.txt](https://github.com/Microsoft/vsts-vscode/files/956363/team-extension1.txt)

I have similar setup as this user
https://github.com/Microsoft/vsts-vscode/issues/185

appreciate all help

**Comment by jeffyoung** [comment]
Hi @Yaash19, thanks for trying out the extension.

You're running into issue #59 that I expect to begin investigating soon.  

I'm going to go ahead and close this issue as a duplicate.  However, I'm interested to know if you're using TFVC and if you already have a local workspace?  The reason I ask is that I see you're setting `team.remoteUrl` and `team.teamProject` (which you only need if your source code is on a server that's different from the server holding your builds and work items).

**Comment by Yaash19** [comment]
Hi @jeffyoung 

Thanks for quick response.

Yes, we have TFVC and already have local work space. Our source code is on a server same as the server holding your builds and work items.

Ok , i will remove team.remoteUrl and team.teamProject from settings. Just fyi,  I get unauthorized error as well when i login into our tfs when i  don't give team.remoteURl and team.teamProject

**Comment by sskasim** [comment]
I am also facing this error "Unauthorized. Check your authentication credentials and try again" and my windows account gets lock after a few attempts. 
I am using the version 1.16.0 of VS Code
