### ISSUE TITLE
Wrong url for action "Team : View history"

### ISSUE THREAD

**Issue by scaillerie** [Microsoft/vsts-vscode#189]
When selecting "Team : View history" in the command palette, I navigate to some url like :
`http://my-tfs-server/tfs/_versionControl?path=...`

If I try to go to the history manually, I found that the url is nearly the same, except there is also the collection name and the project name in the path : 
`http://my-tfs-server/tfs/MyCollection/MyProject/_versionControl?path=...`

**Comment by jeffyoung** [comment]
Hi @scaillerie.  Thanks for trying out the extension.

Can I get you to [enable debugging](https://github.com/Microsoft/vsts-vscode#logging) and provide the output log (team-extension.log)?  Based on what information appears to be missing, I'd expect a lot more to not work.  In the meantime, I'll see if I can reproduce this locally.

**Comment by scaillerie** [comment]
OK, here are the logs : [team-extension.log.txt](https://github.com/Microsoft/vsts-vscode/files/960884/team-extension-saved.log.txt)

**Comment by jeffyoung** [comment]
Thanks @scaillerie.  I was able to reproduce this locally and submitted a fix for it (#194).  It'll go out in the next update (no ETA on that yet).
