### ISSUE TITLE
arg.startsWith is not a function

### ISSUE THREAD

**Issue by garcus** [Microsoft/vsts-vscode#203]
I'm having some trouble using some of functionality of Visual Studio Team Services Extension.
When I enable logging at debug level I see these errors in the log file: 
```
error:  [0908] Error showing pinned query work items arg.startsWith is not a function
```
and
```
error:  [0908] Error showing work item queries arg.startsWith is not a function
```
It seems like there is no problem getting the list of work items but trying to open one from the list generates an error.

I have version 1.11.2 of VSCode and 1.11.7.1 of the extension.
Running on Windows 10.

**Comment by jeffyoung** [comment]
Thanks for the report @garcus.  I've been able to reproduced this and am investigating.
