### ISSUE TITLE
running the contributed command

### ISSUE THREAD

**Issue by iliasjennane** [Microsoft/vsts-vscode#204]
Signing in to VSTS using the extension fails.
![teamextension](https://cloud.githubusercontent.com/assets/13143404/25663345/690dbd78-2fe5-11e7-9e11-843e30c49d25.png)

**Comment by jeffyoung** [comment]
Hi @iliasjennane.

I haven't been able to reproduce this yet.  Can you provide more details as to how you're running the extension (which may provide more clues as to what's going on)? Presumably you're running the latest version of VS Code (and not the Insiders edition)?  Did the extension prompt you to signin or did you run the signin command directly? Which OS are you using?

(I understand you tried re-installing both the extension and VS Code already.) The error you're seeing above is typically an indication that something is catastrophically wrong (like the VSIX didn't full expand under %USERPROFILE%\\.vscode\extensions (on Windows)). Of course, that may not be the case here but we'll have to investigate.

**Comment by Indy411** [comment]
I'm having the same issue with a new install of VS Code with just this extension installed. It happens with every command not just sign in.

**Comment by Indy411** [comment]
OK the issue occurs when you don't have a project open in VS Code. You will also get `(team) No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository.` when you open a TFVC workspace and have not set  `tfvc.location` in settings to point to the TFVC command line. Updating the error messages and documentation may make it clearer for others trying to use the extension.

**Comment by jeffyoung** [comment]
Thanks for the details @Indy411.  I can reproduce this and will investigate.
