### ISSUE TITLE
Required authorization scopes for the Personal Access Token

### ISSUE THREAD

**Issue by Glober777** [Microsoft/vsts-vscode#21]
Hi! I've just installed the extension and find it very handy. I have noticed, however, that there's no mention of a necessary authorization scopes, sufficient for it to work. The configuration example suggests leaving the all scopes enabled by default, but keeping such a powerful access token in the plain text file doesn't seem like a good idea. It would be nice if you had a list of necessary scopes mentioned somewhere in the guide.

Given that the extension mainly reads the data off the VSTS, and _'team create *'_ commands pop up the browser, it seems that the least required list of scopes is:
- vso.build [Build (read)]
- vso.code [Code (read)]
- vso.work [Work items (read)]

Is that sufficient?

Thanks,
Glober777

**Comment by DavidStaheli** [comment]
Thanks, Glober777.  Good point.  Additionally, we should recommend scopes required by any known, upcoming features so that users don't get errors with those features and have to recreate their existing PATs.

**Comment by jeffyoung** [comment]
Can you let me know where you found the "configuration example"?

I have notes in the [README](https://github.com/Microsoft/vsts-vscode/blob/master/README.md), on the [Marketplace page](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team) as well as [on our web site](http://java.visualstudio.com/Downloads/visualstudiocode/Index) that indicate that three levels of (read) required for Build, Code and Work Items.  So, somewhere, I'm accidentally misleading you and I'd like to get that fixed.

Thanks!

**Comment by jeffyoung** [comment]
I should have also mentioned that I did in #20.  After you create a token, you can always go back and update the scopes from "All" to just the "Selected" ones you'd like.  Check out #20.

**Comment by Glober777** [comment]
@jeffyoung, I was referring to the [Set up the Team Services extension for Visual Studio Code](https://www.youtube.com/watch?v=NUVbn7gGLvA) youtube video that is mentioned on the Marketplace page as well as in the README. 

Apparently I was reading too fast and missed the part about required levels jumping directly into the video :)

Thanks!

**Comment by jeffyoung** [comment]
Ah yes, the video!  I completely forgot.  I'll have to figure out a plan as to what to do with that (remove it or update it).

But I appreciate you contacting us about.  Thanks again!
