### ISSUE TITLE
VSO icons duplicated

### ISSUE THREAD

**Issue by kuncevic** [Microsoft/vsts-vscode#216]
That is what I've got:

![image](https://cloud.githubusercontent.com/assets/1283734/25734645/780d14ee-31a8-11e7-8eff-ecc3e4043b16.png)

After I updated to 1.12.1  version

**Comment by jeffyoung** [comment]
Thanks for reporting @kuncevic (this is issue #141). I've got a PR out in #215 that should go out soon.
