### ISSUE TITLE
toggle of activity bar does duplicate some of the status bar icons for VSTS

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/vsts-vscode#218]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.9|
|tslint|eg2|0.12.0|
|JSDocTagComplete|HookyQR|0.0.2|
|docthis|joelday|0.4.4|
|team|ms-vsts|1.117.2|
|vscode-filter-json|richie5um2|1.0.0|
|vscode-sort-json|richie5um2|1.9.0|
|partial-diff|ryu1kn|0.2.0|
|standard|shinnn|0.2.3|
|code-spell-checker|streetsidesoftware|1.1.0|
|JasmineSnippets|xabikos|0.2.1|;

---

icons get duplicated with every toggle. it does not matter if triggered via menu or keyboard short cut.

![image](https://cloud.githubusercontent.com/assets/24651374/25745826/127b6434-31a1-11e7-989f-81ab45767dc3.png)

**Comment by jeffyoung** [comment]
Thanks for reporting @marcelh-gh (this is the same as issue #141). PR #215 has the fix that should go out soon.

**Comment by marcelh-gh** [comment]
great! :-) Thanks!
sorry, I actually had reported this as part of another VS code issue. when they asked me to move this bit of the problem in here, I did not check if it was already reported.

**Comment by jeffyoung** [comment]
Yep, no problem.  (I really wish the VSCode guys would add support for [this](https://github.com/Microsoft/vscode/issues/23325) so we can determine if it is _our_ settings that changed.) The fix is now in 1.117.3 (just released a few minutes ago).
