### ISSUE TITLE
TFS2015 Update 3 could not find a project collection (encoding issue)

### ISSUE THREAD

**Issue by SPWizard01** [Microsoft/vsts-vscode#219]
when trying to open project that i have been working on in VS2015 i get:

> (team) Using SOAP, could not find a project collection some%20name%20withspace at http://mytfsserv:8080/tfs/

i am not even sure i get authenticated, it asks for credentials then the output is quite strange:
[http://puu.sh/vGCP0/b457b2aa87.png](http://puu.sh/vGCP0/b457b2aa87.png)

**Comment by jeffyoung** [comment]
Hi @SPWizard01.

Is there any way you could provide a [debugging log](https://github.com/Microsoft/vsts-vscode#logging)? I have test collections that do have spaces in their names but haven't been able to reproduce this one. (We're attempting to validate the collection name with with the server by making SOAP-based HTTP calls.)

It would also be helpful to see the output of `tf workfold` run from the folder you have open in VS Code.

**Comment by SPWizard01** [comment]
i have actually found out that it is the url encoding that is causing this.
i.e. if i specify:
`"team.remoteUrl":"http://tfssrv:8080/tfs/some project collection"
"team.teamProject":"Some.Project"`

i can see at the bottom that it would connect without issues.
but if i put some%20project into the config it gives me the error.

debugging log does not show anything useful, it does find collection etc, its just the url that is being returned from TF.exe is with "%20"
i.e.:

`tf workfold
===========================
Workspace : MACHINE (User)
Collection : http://tfssrv:8080/tfs/some%20project%20collection
 $/Project.Name: C:\LocalMap
 $/Another.Project: C:\AnotherMap
`

**Comment by jeffyoung** [comment]
Thanks @SPWizard01. Let me set up a repro here locally and have a look. I'll keep this issue updated.

**Comment by jeffyoung** [comment]
Hi @SPWizard01. I was able to reproduce the issue locally and have attached a private fix.  If you're interested, I'd appreciate it if you could [install the attached private drop](https://github.com/Microsoft/vsts-vscode#private-builds) and let me know how it goes.

[team-0.117.3.vsix.zip](https://github.com/Microsoft/vsts-vscode/files/993482/team-0.117.3.vsix.zip)

Thanks!

**Comment by jeffyoung** [comment]
This should be fixed in 1.118.0.
