### ISSUE TITLE
TF.exe missing???

### ISSUE THREAD

**Issue by Allann** [Microsoft/vsts-vscode#222]
I think this is more a question, than an issue.  But I can't get the Team Services integration working.  We are in the process of moving from VS2015 OnPrem to VS2017 Team Services.  We use VS Code to manage our yeoman templates and these have already been moved to Team Services and a local workspace setup.  All works fine from VS2017 including source control integration.  
Today we received the VS Code 1.12.1 update and it mentioned TS source control integration.  We tried to enable it using the video, documentation and release note instructions, but we don't get the prompt for credentials nor the icons in the status bar.
The log output:

> 2017-05-08T02:08:32.448Z - info:   [21744] *** FOLDER: c:\JBSAustralia\Framework\Tooling ***
> 2017-05-08T02:08:32.450Z - info:   [21744] version 1.117.3
> 2017-05-08T02:08:32.450Z - debug:  [21744] Looking for an External Context at c:\JBSAustralia\Framework\Tooling
> 2017-05-08T02:08:32.450Z - debug:  [21744] No External Context at c:\JBSAustralia\Framework\Tooling
> 2017-05-08T02:08:32.452Z - debug:  [21744] Looking for TFVC repository at c:\JBSAustralia\Framework\Tooling
> 2017-05-08T02:08:32.452Z - debug:  [21744] TFVC Creating Tfvc object with localPath='undefined'
> 2017-05-08T02:08:32.452Z - debug:  [21744] Using TFS proxy: undefined
> 2017-05-08T02:08:32.453Z - debug:  [21744] TFVC Retrieved from settings; localPath='undefined'
> 2017-05-08T02:08:32.453Z - warn:   [21744] TFVC Couldn't find where the TF command lives on disk.
> 2017-05-08T02:08:32.453Z - error:  [21744] The path to the TFVC command line (including filename) was not found in the user settings. Please set this value (tfvc.location) and try again.
> 2017-05-08T02:08:58.762Z - info:   [10648] *** FOLDER: c:\JBSAustralia\Framework\Tooling ***
> 2017-05-08T02:08:58.770Z - info:   [10648] version 1.117.3
> 2017-05-08T02:08:58.773Z - debug:  [10648] Looking for an External Context at c:\JBSAustralia\Framework\Tooling
> 2017-05-08T02:08:58.774Z - debug:  [10648] No External Context at c:\JBSAustralia\Framework\Tooling
> 2017-05-08T02:08:58.776Z - debug:  [10648] Looking for TFVC repository at c:\JBSAustralia\Framework\Tooling
> 2017-05-08T02:08:58.776Z - debug:  [10648] TFVC Creating Tfvc object with localPath='undefined'
> 2017-05-08T02:08:58.777Z - debug:  [10648] Using TFS proxy: undefined
> 2017-05-08T02:08:58.778Z - debug:  [10648] TFVC Retrieved from settings; localPath='undefined'
> 2017-05-08T02:08:58.778Z - warn:   [10648] TFVC Couldn't find where the TF command lives on disk.
> 2017-05-08T02:08:58.779Z - error:  [10648] The path to the TFVC command line (including filename) was not found in the user settings. Please set this value (tfvc.location) and try again.

Looking for TF.EXE which is NOT is the workspace we did a full clean and download again, no change, then created a completely new workspace, still no change.  Searching the drive it was located in: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\4p3y0uqx.gwi

No additional files are added to the folder when syncing files from Team Services so not sure how VS Code knows that the files come from Team Services?

We also have VS2015 installed and TF.exe is also in the program file folder structure: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE

**Comment by Rainson12** [comment]
can you try to set your config to: 
"tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe"

**Comment by jeffyoung** [comment]
Hi @Allann, thanks for trying out the extension! (And thanks to @Rainson12 for the assistance!)

The TFVC support in the VS Code extension needs _something_ to provide it information about what files are in your TFVC workspace. That something is either `TF.exe` (on Windows only) or the `Team Explorer Everywhere Command Line Client` (TEE CLC; on Windows, macOS and Linux). So either one or the other needs to be configured. To configure it, you need to set the `tfvc.location` setting in your VS Code Preferences (either User, which will affect any folder you open on disk, or Workspace, which only affects that particular VS Code workspace/folder). That's what @Rainson12 is asking you to set. Details are [here](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#configure-tfvc-support).

FWIW, you can either use the TF.exe that comes with VS 2017 (which should be in the location @Rainson12 points out) or you can use the one under `Microsoft Visual Studio 14.0` so long as it is at least version 14.102.  We will look at the version of TF.exe and let you know if the version meets our minimum requirements.  If not, you should get an error dialog with a message similar to `The configured version of TF does not meet the minimum version. You may run into errors or limitations with certain commands until you upgrade. Minimum version: ` and a `Get Latest VS 2015 Update` button that will take you [here](https://msdn.microsoft.com/en-us/library/mt752379.aspx) to get the latest 14.0-based version of TF.exe.

Let me know if either of these works (or doesn't) for you.

**Comment by Allann** [comment]
That worked, thank you.  Might be worth adding that as a first step in the doco.  I tried this at home on a brand new install, and had to go through the same process.

**Comment by rfcfore** [comment]
@microsoft this was disruptive to automation.  please wait until next major release to switch around paths to build tools.  thanks.
