### ISSUE TITLE
error trying to perform any command

### ISSUE THREAD

**Issue by rspaulino** [Microsoft/vsts-vscode#24]
running latest version of macOS
running latest version of vscode
running git-creditial-manager

I have install and configure the vsts extension for visual studio code but every time I try to perform any command I get a 404 error. The url don't seen to match I don't know if this is part of the problem or they are just different because this are API call

vscode error: (team) Failed Request: Not Found(404) - https://*****consulting.visualstudio.com/*****Consulting/_apis/git

vsts working url: https://*****consulting.visualstudio.com/_git/aspnetcore

<img width="375" alt="screen shot 2016-07-09 at 12 57 55 am" src="https://cloud.githubusercontent.com/assets/378671/16706186/7665de7a-4570-11e6-8f7a-9db4eecd8751.png">

<img width="298" alt="screen shot 2016-07-09 at 1 01 01 am" src="https://cloud.githubusercontent.com/assets/378671/16706193/a5d8b4a2-4570-11e6-81df-7ff9dbc17c31.png">

**Comment by jeffyoung** [comment]
Thanks for reporting.  It appears the URLs to the REST endpoints are getting set incorrectly.  Could I ask you to turn [on the logging](https://github.com/Microsoft/vsts-vscode/blob/master/README.md#logging), repro the issue and send the log file to me at jeyou at microsoft dot com?  I'd like to take a look and see what's going wrong.

Also, is the URL segment after ".visualstudio.com/" the same as the name of your account?  That is, is "**consulting" and "**Consulting" the same value?

Thanks!

**Comment by rspaulino** [comment]
@jeffyoung thank, I have sent you the log, let me know if you got it.

Yes but that is the one where I get the 404 error.

**Comment by jeffyoung** [comment]
Thanks!  I've taken a look at the log and sent you a private fix which I hope will get you around the issue.  I'll need to test it a bit more but submitting it.

**Comment by jeffyoung** [comment]
Thanks for verifying the fix.  I'll get more testing done and get a PR some time soon.

**Comment by jeffyoung** [comment]
Should now be fixed in release 104.
