### ISSUE TITLE
What do the colored letter icons mean next to file names?

### ISSUE THREAD

**Issue by Kss113** [Microsoft/vsts-vscode#252]
What do the colored letter icons mean next to file names?
![icons](https://user-images.githubusercontent.com/29436445/27141397-09dd4d46-50f6-11e7-930f-294a045b83ee.png)

If the image came through then it's the green A Icon next to the force.jason file and Blue E icon next to package.xml.

**Comment by jpricketMSFT** [comment]
A => Add - a new file added to the repo (these may be generated files that you want to add to the tfignore file)
E => Edit - an existing file was edited in the repo
