### ISSUE TITLE
"Logging is disabled" message in Console

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vsts-vscode#263]
With the VSTS extension loaded and when debugging another extension, the VSTS extension is outputting a "Logging is disabled" message to VS Code's debug console.

This is confusing when developing other extensions as it is not clear where this message is coming from. It was especially confusing when you hit this issue: https://github.com/bradygaster/azure-tools-vscode/issues/46 :)

**Comment by chrisdias** [comment]
This looks to be the offending line:

https://github.com/Microsoft/vsts-vscode/blob/master/src/extensionmanager.ts#L503

**Comment by jeffyoung** [comment]
Thanks @chrisdias.  I'll go ahead and remove that line (as I think I only added it when I introduced logging quite a ways back).  Sorry about causing a confusing debugging experience in that other issue. 😄

**Comment by jeffyoung** [comment]
Resolved in 1.119.1
