### ISSUE TITLE
Recognize when local folder is pushed to team project

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vsts-vscode#27]
The extension recognizes when a local git repository is also a remote repository in VSTS but it does not recognize when the folder becomes a remote repository unless I change a setting or reload VS Code.

Here's how to repro:

- ensure you have your PAT set up
- create a new folder, new file, and commit it to a git repo:

``` bash
mkdir a1b2c3 
cd a1b2c3  
echo "VSTS Rocks" >> ./test.txt 
git init 
git add . 
git commit -m "initial commit" 
code .
```

-create a new team project in VSTS, which creates a corresponding git repository
- in the terminal, push the local repository to VSTS (replacing XXXXX with the appropriate account and repo):

``` bash
git remote add origin https://XXXXXX.visualstudio.com/DefaultCollection/_git/XXXXXX
git push -u origin --all
```

**Result**

In VS Code (regardless of the pollingInterval setting) the extension never recognizes that the repository is now in VSTS.  If you change a setting (e.g. set pollingInterval = 1) then the extension reinitializes and the folder is recognized as a VSTS repo.  Alternatively you can refresh VS Code which reloads the extension.

**Expected**

It would be ideal for the extension to automatically recognize that the repository is now in VSTS. I expected that when the extension polled it would figure this out. Ideally it is instant and I don't have to wait 1-5 min. Perhaps you can have a file watcher for a .git folder.

**Comment by jeffyoung** [comment]
I pushed the changes needed for this functionality in release 104.  Please let me know if you have issues with this scenario again.  Thanks @chrisdias

**Comment by chrisdias** [comment]
looks good!
