### ISSUE TITLE
TFS do not show or include files outside of currently opened project/folder

### ISSUE THREAD

**Issue by abdulkareemnalband** [Microsoft/vsts-vscode#273]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- VSTS-VSCode Verison: team 1.119.0
- TF version: TF - Team Foundation Version Control Tool, Version 15.112.26421.0

Steps to Reproduce:

1. Checkout a project with multiple visual studio projects,(let assume there is project `A` and project `B`)
2. Edit files in `A` (by any means)
3. Open project `B` in vscode
4. Switch to `Source Control` view
5. Changed files from project `A` are shown here

Desired Outcome
Only files belonging to project `B` should be shown if current work space is root is project `B`

**Comment by jeffyoung** [comment]
Hi @abdulkareemnalband, thanks for trying out the extension!

You can get the behavior you desire by setting the `tfvc.restrictWorkspace` setting in Visual Studio Code.  It is provided by this extension (and you can read more about it [here](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#restricting-status-changes-to-the-current-vs-code-workspace)). 

Let me know if this provides (or doesn't provide) the behavior you were expecting.

**Comment by abdulkareemnalband** [comment]
Thanks for hint,
It works
