### ISSUE TITLE
Continual Info bar popup

### ISSUE THREAD

**Issue by jdrake3** [Microsoft/vsts-vscode#277]
No matter which option (except 'Don't Show Again') I choose the Info bar continues to pop.  It pops whenever I change the color scheme, or open a folder, or basically anything but opening a file in the editor.

OS: Win 10
OS Version: 1511 (Build 10586.962)
VS Code Version: 1.13.1
Team Service extension: 1.119.1

![mscode](https://user-images.githubusercontent.com/1247320/27927980-812bf9bc-625b-11e7-88f1-bc22b36f47b3.png)

**Comment by jeffyoung** [comment]
Thanks for filing the issue for this @jdrake3.  I'm going to push (and release) a quick fix shortly.

**Comment by jeffyoung** [comment]
Thanks @jdrake3.  I just published 1.119.2 that should address this issue.  Please re-open if you don't see the behavior you expect.

**Comment by jdrake3** [comment]
Fix Verified.

Thank you.

**Comment by jdrake3** [comment]
Hate to do this to you, but today I chose **Install Additional Color Themes** on the menu, and the popup is back when I select a newly added one:
![image](https://user-images.githubusercontent.com/1247320/28088581-1acb4298-6654-11e7-8177-005ad30bb9c9.png)
