### ISSUE TITLE
(team) socket hang up / (team) undefined after switch to Azure VM

### ISSUE THREAD

**Issue by EvtK** [Microsoft/vsts-vscode#288]
Hi,

I have been succesfully using the plugin to connect to a TFS 2015 update 2.1. This was on a internal network where I was connecting from a virtual machine to the TFS environment (both internal).

We have now switched to the Azure platform, which is external of course. While making the connection from the Azure VM to our TFS server, I get these errors:

(team) undefined
(team) socket hang up

As far as we know, the firewall has been configured correctly for use of our TFS server. Since I can connect to TFS by simply browsing to the webinterface from my Azure VM.

Are there any specific ports we need to open to be able to use the plugin. Or is any additional configuration needed?

Thanks!

**Comment by EvtK** [comment]
We haven't booked any progress on this. Is there anyone out here who can help us out or assist us in anyway? Thanks.

**Comment by guilala** [comment]
I am trying to have azure-repos-vscode login to a custom tfs server. I can enter my domain\user and passrod, but after that i also get '(team) socket hang up'. Like this, TFS is NOT supported in VS Code...
