### ISSUE TITLE
Impossible to switch to TFS

### ISSUE THREAD

**Issue by Kris-I** [Microsoft/vsts-vscode#290]
Hello,

I installed this extension. When I go to View -> SCM  only Git is available. I tried to reinstall several times but without any success. 

On the top ow the window there is info message : "(team) Welcome to version 1.121.1 of the Team Services extensions" with 3 options "Learn more", "Set up TFVC support ..." and "Don't show again". When I click on "Set up TFVC support"  direct me to "Quick Started" page.

In the "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer" there is no TF.EXE

But when I open a "Developer Command prompt for VS2017", the command "tf vc help" give me the help information.

Could you help me ?

thanks,

**Comment by jeffyoung** [comment]
Thanks for trying out the extension @Kris-I (and @Kiruchi).

The [Quick Start](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#quick-start) indicates that you need to set the `tfvc.location` setting to the full path to TF.exe. In the developer command prompt window you opened, type `where tf.exe` to get that location.  See this [FAQ](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#i-already-have-visual-studio-installed-how-can-i-determine-the-location-of-tfexe).
