### ISSUE TITLE
Visual Studio authentication popup 

### ISSUE THREAD

**Issue by csahut** [Microsoft/vsts-vscode#303]
Hi,

I'm working with your extension + Visual Studio Team Services and for some reason, I get endlessly the attached popup asking to authenticate on Visual Studio. If I enter my credentials, it works but the popup appears again a few minutes later. If I discard the popup (close it), it also come back again later.

I can pull/push code and sync with VisualStudio Team Services from Visual Studio Code without any problem so the authentication is probably fine. It's just that this window pop-up is really annoying.

![auth](https://user-images.githubusercontent.com/1764319/29399339-1e3f39b0-8329-11e7-868a-4d406c7cdfd4.png)

I tried the two types of authentication (old and new) mentioned in your documentation, I do see the tokens on the web UI, and I think they are fine as I can sync my repos. I'm not sure what triggers this popup but if I disable your extension, I don't have it anymore.

Any idea to fix this problem?

Thanks,

**Comment by csahut** [comment]
It seems related to https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/424 .

Installing last version (https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.12.0 at the time of writing) seems to fix the issue.

**Comment by csahut** [comment]
Well, closed it to early. Last version does not solve the problem.

**Comment by jeffyoung** [comment]
Hi @csahut.  The login dialog you provided a screenshot for isn't one provided by the extension.  Like you mentioned, it likely has to do with the GCM for Windows.  That said, it'd be great if you could confirm that the dialog still appears after disabling or uninstalling the extension.  (The only 'external' dialog that would be popped up by the extension would be for the new 'automatic signin' process for Team Services, also known as 'device flow'... but it wouldn't happen randomly.  It would only appear after you chose to use that option.)

**Comment by whoisj** [comment]
@csahut @jeffyoung the dialog is actually provided by [ADAL for .NET](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) and just made available to Git for Windows via the GCM.

@csahut are you performing some kind of credential caching in your application?

@jeffyoung can you think of any reason VSCode users would be seeing this many GCM issues? No other application has as many issues as VSCode does (from the point-of-view of the GCM).
