### ISSUE TITLE
Soap Service error - can't connect to TFS Projects from company server

### ISSUE THREAD

**Issue by minaaboud** [Microsoft/vsts-vscode#304]
Hello, 

I have followed the instruction and had help from other two devs following the same instruction, but every time we are stuck at this error every time I'm trying to connect to a project and get it. 

![screen shot 2017-08-18 at 9 00 45 pm](https://user-images.githubusercontent.com/8300058/29473829-90b0bbfa-8459-11e7-8aef-8b0c3209869b.png)

Any idea ? also I'm still getting setup TFVC in VS code every time I load the local folder!

I got the workspace created and get the projects locally using Eclipse.

**Comment by jeffyoung** [comment]
Hi @minaaboud.  It appears you're sending a **_team project URL_** to the collection argument of 'tf status'.  You'll need to send a **_collection_** URL like `tf status -collection:"http://servernmae:port/tfs/defaultcollection"` (whatever URL matches your collection; likely what you covered in your screenshot).

As far as "also I'm still getting setup TFVC in VS code every time I load the local folder!", could you enable (debug logging)[https://github.com/Microsoft/vsts-vscode#logging] and provide the team-extension.log file here?  The debug log should contain additional information so we can troubleshoot the problem.
