### ISSUE TITLE
Get latest source code from TFS

### ISSUE THREAD

**Issue by joekytse** [Microsoft/vsts-vscode#305]
Hi there, thanks for providing this great tool. It provides a convenient way to work with the TFS.

I just setup a new project on TFS and was able to check-in changes to the TFS following the instructions with it using Visual Studio Code. But how can I get latest source code from TFS (in the same way as visual studio)?
I couldn't find any matching command by typing "team" in the command palette, and also didn't see any relevant commands in the official page too...
https://marketplace.visualstudio.com/items?itemName=ms-vsts.team

I am using version 1.122.0. Any help is appreciated

------------------
Edit:
right now I'm running the TF command in terminal to get the latest souce code:
tf get "$/<FOLDER ON TFS>" /recursive

is there another way provided by the tool?

**Comment by jeffyoung** [comment]
Hi @joekytse.  Thanks for using the extension.

Yes, you can get the latest code from the server by using the "Sync" command found off of the "..." menu on the SCM Viewlet.  Many of the commands are provided via the SCM viewlet UI.
![image](https://user-images.githubusercontent.com/2796865/29671803-6b985bd0-88b8-11e7-959f-2804c8f1120b.png)

There aren't too many commands for tfvc provided in the command palette, but if you use the 'TFVC' prefix, you'll see that `Sync` is one of them:
![image](https://user-images.githubusercontent.com/2796865/29671906-bfaa8c7a-88b8-11e7-9833-e6d06e9fd537.png)

Finally, if you haven't seen them yet, there are 'Getting Started Videos' listed at https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#getting-started-videos.  The first is an overview of the TFVC support.

**Comment by joekytse** [comment]
Hi @jeffyoung 
Thanks a lot for the info. I completely missed that function lol

**Comment by jeffyoung** [comment]
Glad you got it sorted! 😄
