### ISSUE TITLE
Unable to find the TF executable

### ISSUE THREAD

**Issue by gleb-svechnikov** [Microsoft/vsts-vscode#317]
Hello I've followed your instruction, but got this error:

> (team) Unable to find the TF executable. Please ensure TF is installed and the path specified contains the filename. Provided path: /usr/local/bin/TEE-CLC-14.123.1/

TF works and I accepted EULA and set workspace collection

OS: CentOS version 7, VS Code version 1.16.0

![screenshot from 2017-09-21 17-52-54](https://user-images.githubusercontent.com/500843/30702477-bc023fa2-9ef5-11e7-9d94-7bea7283aa6e.png)
Could you help to understand what is wrong?

**Comment by kaylangan** [comment]
@gleb-svechnikov can you try updating the tfvc.location setting to the full path to tf.cmd (e.g., /usr/local/bin/TEE-CLC-14.123.1/**tf.cmd**)?

**Comment by kaylangan** [comment]
@gleb-svechnikov I'm going to close this issue. If specifying the full path didn't work, please let me know. Thanks!
