### ISSUE TITLE
Proxy Server Settings

### ISSUE THREAD

**Issue by Lowestkillcount** [Microsoft/vsts-vscode#319]
Hi All, 

Trying to use VSTS Connection behind a proxy. 

The Extension doesn't seem to be honoring the Proxy settings set in the VScode config - nor the machines settings. 

Not sure if this is a bug with the extension or in VScodes implementation of proxies.

**Comment by tylerbhughes** [comment]
I'm having the same problem. As @Lowestkillcount said the extension doesn't seem to be honoring the proxy settings I've got set in VS Code under user settings.

**Comment by jimsleon** [comment]
I am encountering same issue, I could connect to VSTS from browser, Visual Studio Enterprise but not VS code. This issue opened for 3 months, why no comments for workaround?

**Comment by kaylangan** [comment]
@Lowestkillcount I'm going to close and dupe this to #324 since that issue has a log that we can investigate. Please let me know if you think that this issue is different.

**Comment by svendebaets** [comment]
Why did you close this issue without proposing a solution? We have the same problem behind a corporate firewall. We tried configuring http.proxy but without success. 
When I look around, I find two approaches to configure a proxy in VS Code. One is to configure http.proxy in the VS Code settings. Another is to configure a proxy on Chromium. Which one is the correct approach?
