### ISSUE TITLE
VSTS PAT

### ISSUE THREAD

**Issue by rbergelm** [Microsoft/vsts-vscode#327]
I have PATS Personal Access Token that are expiring within 2 weeks and I have NOT received any notifications.
 
These tokens were for 1 year.  The 1 year term does not enable the save button to renew.  The save button is only enabled if I change term to a shorter term like 90 days or 180 days.

How do I make sure I receive notifications?
 
How do I renew for 1 year?

**Comment by peakyy** [comment]
Hi,

Unfortunately, today VSTS does not have notfications for PAT expiry. It is a piece of work we know many customers are asking about and we have added the work to our backlogs. In addition to PAT notifications we also plan on updating the UI to make action like PAT renewal more straightforward.

Today to renew a PAT (the PAT can be be expired, non-expired, or revoked) go to the PAT UI under the security tab and edit the PAT by clicking on its name. There you should see the current duration and the scoping of the PAT. To renew you must change the duration to any other duration (in your case 90 or 180 days) and save the PAT. Doing this renews the PAT for the selected duration. If you want to renew with the same duration (like 1 year) then edit the PAT again and change the duration to 1 year and it will renew for the next year.
