### ISSUE TITLE
Git repositories cloned from VSTS/visualstudio.com using the "new" url aren't detected by the vsts extension

### ISSUE THREAD

**Issue by aberghage** [Microsoft/vsts-vscode#333]
Like the title says, if you clone a git repo from VSTS with the old `ssh://acctname@acctname.visualstudio.com:22/DefaultCollection/_git/reponame` URL, the vscode vsts extension will correctly detect it as a vsts repo. If, on the other hand, you update the remote to the new `ssh://acctname@vs-ssh.visualstudio.com:22/DefaultCollection/_ssh/reponame` format, the extension won't recognize it as a vsts workspace.

I checked for updates to the extension -- there don't appear to be any. For the time being I've just switched back to the old URL scheme, but as the giant deprecation banner warns when pulling from it, it's going away on the 17th.

It looks like the parsing code begins [here](https://github.com/Microsoft/vsts-vscode/blob/master/src/contexts/gitcontext.ts#L68) and eventually winds up [here](https://github.com/Microsoft/vsts-vscode/blob/master/src/helpers/repoutils.ts#L25). Since the VSTS clone URLs now use _ssh for that segment of the path, this won't cut it anymore.

**Comment by aberghage** [comment]
I skimmed the open issues and PRs, doesn't look like this has been addressed yet, so I'll cut a PR quickly to remove the nesting (since clearly a git repo cloned from visualstudio.com is a VSTS repo)

**Comment by aberghage** [comment]
Closed by merging #334.

**Comment by hammady** [comment]
Unfortunately, the ssh URLs has changed again to something like:
`acctname@vs-ssh.visualstudio.com:v3/acctname/DefaultCollection/reponame` which breaks the detection (again).

**Comment by hammady** [comment]
This URL should work: `git@vs-ssh.visualstudio.com:v3/acctname/DefaultCollection/reponame`
