### ISSUE TITLE
@CurrentIteration doesn't seem to be working pinned queries

### ISSUE THREAD

**Issue by IThordGray** [Microsoft/vsts-vscode#337]
When setting up "team.pinnedQueries" in VSCode preferences, if the query uses @CurrentIteration, the results are 0. If I replace with @CurrentIteration with a hardcoded string iteration path value, it returns the correct items. 
Using @CurrentIteration on VSTS works fine though.

Tested using queryText (my own select statement) and queryPath (vsts saved query), both giving the same issue with @CurrentIteration or same results using hardcode IterationPath.

**Comment by kaylangan** [comment]
Can you try updating the query on VSTS that uses @currentIteration and also provide the team parameter and see if that resolves the issue?

**Comment by IThordGray** [comment]
Hi there,

Thank you. I've explicitly added the team parameter to my Query on VSTS and that seems to have resolved the issue. Thank you for the feedback.
