### ISSUE TITLE
VSCode recommends this because I have git installed?

### ISSUE THREAD

**Issue by markdall** [Microsoft/vsts-vscode#338]
VSCode recommends this because I have git installed? I realize vsts includes TFS which includes git support but that doesn't mean I use Visual Studio Team Services. 

VSCode includes built-in git support, what sense does it make to recommend this extension? 

Please note: This isn't a complaint: I'm trying to understand or, if I'm understanding correctly, trying to get you to clarify why someone using VSCode and Git but not VSTS needs this extension and if they do not, to stop recommending it. 

Thanks in advance!

**Comment by kaylangan** [comment]
@markdall if you do not use VSTS, TFS, or TFVC, then you do not need this extension. You are correct that VS Code offers native Git functionality.

**Comment by markdall** [comment]
@kaylangan We do use TFS, we just don't use TFS for source control. Not my decision. It's disappointing to know that my favorite text editor will never stop soliciting me to install this addon that will be of no use to me. :(

**Comment by kaylangan** [comment]
@markdall got it. For what it's worth, the extension also has some build and work item integration. I do get the feedback though. Unfortunately, VS Code (and not this plugin) controls which extensions are suggested.
