### ISSUE TITLE
The associate work item, not populating commit message

### ISSUE THREAD

**Issue by MilesHart** [Microsoft/vsts-vscode#341]
The youtube tute shows how to associate a work item, but this doesn't seem to work.

https://youtu.be/sk6LrzQX4P8?t=5m53s

The commit message remains blank.

**Comment by MilesHart** [comment]
If you manually add the "#{bug item}" then this works as prescribed.

**Comment by dougrday** [comment]
Duplicate of #314

**Comment by kaylangan** [comment]
This is a duplicate of #314
