### ISSUE TITLE
There's no audio with the TFVC Source Code Control in Visual Studio Code video

### ISSUE THREAD

**Issue by rfalanga** [Microsoft/vsts-vscode#363]
I'm trying to set up TFVC within VS Code on my laptop. went to this main page for this repo and followed the link titled "TFVC Source Code Control in Visual Studio Code", which took me to YouTube. The video started to place. No sound at all. Didn't matter what browser I used, no sound. I tried other videos on YouTube - they all worked fine. It's just "TFVC Source Code Control in Visual Studio Code" video which had no sound. If this video anywhere else so I can watch *and* hear it?

**Comment by kaylangan** [comment]
Assuming you're referring to [this video](https://www.youtube.com/watch?v=6IzJ2UPGmoQ&feature=youtu.be), I can't reproduce. I hear audio.

**Comment by rfalanga** [comment]
OK, thank you Kaylangan.
