### ISSUE TITLE
VSTS does not prompt for credentials when adding a TFS folder

### ISSUE THREAD

**Issue by imacmullin** [Microsoft/vsts-vscode#368]
Hello,

I am running the following software & extension:

Visual Studio Code Version 1.19.3
Visual Studio Team Services 1.122.0

My issue is that when opening a workspace folder the extension is not prompting me to add a personal access token. When I attempt to run `team:signin`, I receive the following error:

No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository.

**Comment by sabithasharma** [comment]
Hi Imacmullin,
      May I know what was the fix? Even I am facing the same issue.

Thanks in advance.
