### ISSUE TITLE
What is the future of this extension?

### ISSUE THREAD

**Issue by msalti** [Microsoft/vsts-vscode#370]
Hi All,

My team and I have been using VS code for sometime now and love it.  This extension makes our lives a lot easier, but there is a lot to be desired... Can someone please let me know if this extension will continue to be updated? 

Thanks!

**Comment by kaylangan** [comment]
@msalti 
Yes, this extension will continue to be updated. However, we will not be updating it as frequently as in the past. We are always open to community contributions, so if you have features you'd like to add, please submit a pull request!
