### ISSUE TITLE
VSTS modal dialog close event

### ISSUE THREAD

**Issue by javeriaanwer** [Microsoft/vsts-vscode#390]
Hi,

I am using microsoft VSTS modal [dialog ](https://docs.microsoft.com/en-us/vsts/extend/reference/client/controls/modaldialog?view=vsts)and I want a confirmation message when modal dialog is closed from 'x' (closed button of modal dialog), I get close event which fired after event dialog is closed.

I want an event before closing the dialog. How can I do that?

here is the code:
```
VSS.getService(VSS.ServiceIds.Dialog).then(function(dialogService) 
{ 
       var contributionId = //id 
       var dialogOptions = { title: "ABC", close: onDialogCloseByCrossButtonClick }; 
       dialogService.openDialog(contributionId, dialogOptions).then(
               function (dialog) {
                    // do something
        });
}
```

like its appearing in TFS WorkItem window.

![image](https://user-images.githubusercontent.com/25203829/38791311-5fd6c05a-4160-11e8-8e8c-1ffb6f76df4e.png)

**Comment by kaylangan** [comment]
@javeriaanwer This project is for the VSTS extension in VS Code. You can try asking this question on https://www.visualstudio.com/team-services/support/ .
