### ISSUE TITLE
Can't connect to TFS 2015 OnPremise

### ISSUE THREAD

**Issue by maximpashuk** [Microsoft/vsts-vscode#41]
I am using TFS 2015 OnPremise version 14.95.25229.0

According to [this link](https://blogs.msdn.microsoft.com/tfssetup/2013/11/21/what-version-of-team-foundation-server-do-i-have/) it is Update 2.1 for TFS2015, so it should be supported by vsts extension.

On 'team login' command I get following error
![1](https://cloud.githubusercontent.com/assets/5028850/17356301/d3c428dc-5980-11e6-9957-5109392c6116.png)

I don't know how can I diagnose why I can't ```team login``` to my TFS OnPremise account.

I can create pull request in TFS OnPremise using VS2015 or web interface, but not using VSCode.
If it helps, any git stuff works perfectly from VSCode to TFS OnPremise (fetch\pull\commit\push)
Also I can ```team login``` to TFS Online without any problems using access token.

**Comment by jeffyoung** [comment]
Hi Maxim.  Thanks for trying out the extension (but I'm sorry you ran into this issue).

I've investigated and know what the issue is.  I'll need to refactor a little but should be able to push out an update soon (in the next day).

**Comment by jeffyoung** [comment]
I just published a new version (1.104.1) with changes that should allow you to access your TFS server.  Please give that version a try and let me know the results.  Thanks Maxim!

**Comment by DCstewieG** [comment]
Quick work, thanks! This version now detects my TFS. However, I can't login. The log shows this:
```
2016-08-03T20:41:25.632Z - info: Getting repository information (vsts/info) with repositoryClient
2016-08-03T20:41:25.632Z - debug: RemoteUrl = https://<myRepoUrl>
2016-08-03T20:41:25.884Z - error: unable to get local issuer certificate
```
I understand this is probably a separate issue, especially if Maxim reports success.

**Comment by maximpashuk** [comment]
Wow, I not expected that fix will comу so fast.

I checked out, now 'team login' works just fine - pull requests, builds, work items - all things detected correctly.

I close my issue.

PS. Does any body know if the same kind of extension available for GitHub?

**Comment by maximpashuk** [comment]
Answer to myself.
For GitHub https://marketplace.visualstudio.com/items?itemName=HookyQR.GitHubIssues is the goodone/

**Comment by scote** [comment]
I have the same issue as @maximpashuk. My TFS server is detected but I can't connect to it.

```
error: Failed (vsts/info) call with repositoryClient:  Unauthorized. Check your authentication credentials and try again.
```
