### ISSUE TITLE
TFVC only shows changes for one folder

### ISSUE THREAD

**Issue by nategreen** [Microsoft/vsts-vscode#426]
Multiple folders can be open in the VS Code workspace, but I can only see changes in TFVC for one of them (the first one in my list), and it doesn't seem like I can change which one. If I'm not mistaken this is a fairly new feature for VS Code so I suspect this plugin just hasn't caught up yet.  In case you don't know what I mean, more detail is below.

Let's say I have three projects in my workspace:
```
mri-ux
mri-sass
mri-icons
```

When I run any of the TFVC commands from the palette, I see something like this in the output:
```
tf status -noprompt -collection:https://<our TFS URL> ******** -format:detailed -recursive c:\path\to\mri-ux
tf resolve -noprompt ******** c:\dev\mri-ux -recursive -preview
```

Note that it only shows the path to one of the projects. The only way I can seem to change what shows up in the source control panel is to change the order of the folders in the workspace. If I reorder them so `mri-icons` is first, then I see this in the output:

```
tf status -noprompt -collection:https://<our TFS URL> ******** -format:detailed -recursive c:\path\to\mri-icons
tf resolve -noprompt ******** c:\path\to\mri-icons -recursive -preview
```

**Comment by nebmesemaou** [comment]
+1

**Comment by kaylangan** [comment]
Closing as dup of #339
