### ISSUE TITLE
Associate work items with Git commit/push

### ISSUE THREAD

**Issue by millicandavid** [Microsoft/vsts-vscode#43]
My team is wanting to enforce that all commits are associated with a Team work item. To do so today I have to open Visual Studio 2015 just to do my commits which is awful. It would be great to have this integrated somehow and this plugin seems like a better place than VS Code.

**Comment by jeffyoung** [comment]
Hi @millicandavid.

Have you seen the information on [branch policies](https://www.visualstudio.com/en-us/docs/git/branch-policies)?  That documentation doesn't talk about it but, in my Team Services account, there's a policy for "Work item linking requirements":

![image](https://cloud.githubusercontent.com/assets/2796865/17406555/e7f8d6ca-5a31-11e6-8dfc-0c0365cadbdb.png)

I've not used that particular feature but perhaps it's what you're looking for?

**Comment by millicandavid** [comment]
Sorry but I think I didn't make what I was requesting clear enough. What I want to be able to do is associate my git commit with a Team work item when I make the commit. In VS 2015 the option is there when you go to make a commit. I just haven't seen how to do it in VS Code or in this plugin. So my team wants to do what you are pointing to but I want to be able to comply with that policy within VS Code. Does that make sense?

**Comment by AlexRukhlin** [comment]
Hi,

You might add a work item mention (in form #nnnnnnn where nnnnnnn is the work item ID) somewhere in the commit's comment. 

e.g.

   This commit fixes the issue described in the bug #31415 

or

Tasks #271828, #31415, and #98066 are completed with this commit

That mentions are processed on the server and commits will be associated with the corresponding work items. Would that help you?

Alex

**Comment by millicandavid** [comment]
Yes Alex, I'm an idiot. Thanks. I can't believe I'd forgotten this. Please ignore my request.

**Comment by viveksharan** [comment]
Alex, I Used Source Tree to add the Commit Comment and added the #ID in the comment.

When I go to  https://myproject.visualstudio.com and pul up the issue #ID, I still do not see anything linked associated to that work Item. 

Any ideas if I am doing something wrong or if this scenario will work ?

**Comment by mayeager22** [comment]
I am in VSTS with Visual Studio 2017.  I put #3 in a commit comment, but did not see the link in User Story #3.  Did something get broken with this functionality?

**Comment by kaylangan** [comment]
@mayeager22 please refer to #314
