### ISSUE TITLE
"Azure Repos" extension not found in search

### ISSUE THREAD

**Issue by turbolego** [Microsoft/vsts-vscode#440]
Windows 10
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

According to the install guide in the readme:

>To install the extension with the latest version of Visual Studio Code (version 1.11.1 is the latest as of this writing), bring up the Visual Studio Code Command Palette (F1), type install and choose Extensions: Install Extensions. In the Search Extensions in Marketplace text box, type team. Find the Azure Repos extension published by Microsoft and click the Install button. Restart Visual Studio Code.

when searching for "team @sort:name" there are no extensions named "Azure Repos".

![screenshot_479](https://user-images.githubusercontent.com/2650749/46530371-c8d8c100-c899-11e8-8a84-5102001a6e64.png)

**Comment by CaringIsCreepy** [comment]
It seems like the install guide should be updated with the Azure DevOps rename change here: https://github.com/Microsoft/azure-repos-vscode/commit/a22e6f38c7d758e022211a33cbd928c943915f6f

In that commit it still recommends type `team` ... once the Azure DevOps change-over is released, that should probably recommend something like `Azure DevOps` or `Azure Repos`

**Comment by jrbriggs** [comment]
The extension has been republished as "Azure Repos". Thanks for raising this issue!
