### ISSUE TITLE
Support projects where the git repository is not on VSTS

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vsts-vscode#46]
We're using VSTS with a couple of different projects to track work items and do builds and releases. Since these projects are open-source, they are hosted on Github.

Unfortunately, the current version of this repo does not support this scenario at all. It would be nice to still see work items and build status, even if the repository itself is not hosted on VSTS.

**Comment by jeffyoung** [comment]
Hi Lukas.

Thanks for giving the extension a try and for your suggestion.

The extension uses the repository's remote origin URL as the basis for what to connect to.  As you've experienced, when the repo is on GitHub the extension doesn't load so you don't get any Team Services info.  I'd have to figure out a good way to allow users to map a GH repo to a Team Services team project (and provide the corresponding PAT, if it didn't exist yet) then use that information to connect for just WIT and Build.

This is a feature I can spend some time thinking about but don't have any kind of ETA.

**Comment by lumaxis** [comment]
Thanks @jeffyoung, having this be considered as a future enhancement is all I can ask for 🙂👍

**Comment by aarcro** [comment]
It would be great if you could scan all the remotes for visualstudio.com domains, or just the the user pick which remote to use to talk to teamservices. I too would like to have my origin on github and point a different remote to team services

**Comment by jeffyoung** [comment]
Hi @lumaxis and @aarcro.  We just released v1.113.0 that we hope contains the support you're looking for.  After updating the extension (which now requires VS Code 1.7+), have a look at our notes at https://github.com/Microsoft/vsts-vscode#using-external-non-microsoft-source-repositories on how to set it up.  If you have questions or find issues, feel free to open a new issue.  Thanks!

**Comment by lumaxis** [comment]
Yay, this looks excellent @jeffyoung ! 🎉  Many thanks for adding this, very much looking forward to giving it a spin over the next couple of days 👌
