### ISSUE TITLE
Unable to connect to VSTS

### ISSUE THREAD

**Issue by evanportwood** [Microsoft/vsts-vscode#51]
Using v1.5, I have provided my access token which appeared to be accepted, but looking in the status bar the extension shows that the connection has been refused.  I have already set my proxy in user.settings, and do not have any other issues with accessing extensions, but I'm still unable to connect to VSTS.

Does this extension use this proxy information?

![econnrefused](https://cloud.githubusercontent.com/assets/96517/18562485/db8c57f4-7b51-11e6-945d-c470b34efab0.png)

**Comment by jeffyoung** [comment]
Hi @evanportwood.  Today, the extension doesn't support using a proxy so you're seeing behavior similar to #19.

However, I just took a look at the PR that was blocking the use of the proxy in vsts-node-api and it appears to have been merged (relatively) recently.  The current version of the VS Code extension, 1.104.1, is using v3.1.1 of the vsts-node-api.  In v4 of the vsts-node-api, a breaking change was made in which the API was moved from a Q.Promises or callback model to the async/await model.  It was after that major version change was made that the PR I was blocked on was merged.  Therefore, what I need to do is the work to take the latest version of the vsts-node-api and update the extension.

At this point I don't have an ETA for when that will get done but I'll make it a high priority (ideally it'll be in the next release).  Thanks for asking (and for trying out the extension)!

**Comment by evanportwood** [comment]
Thanks for the quick and informative feedback!  I appreciate you making
this a priority and look forward to the update.

**Comment by jeffyoung** [comment]
Hi @evanportwood.  The vsts-node-api added some support for proxies (just not authenticated proxies) and this should be able to work at this time (a bit more information at https://github.com/Microsoft/vsts-vscode/issues/19).  I'd be interested in hearing about your experience with an updated extension.  Apologies for taking so long to update the issue.

**Comment by jeffyoung** [comment]
At this point, an unauthenticated proxy should work (by setting http_proxy and https_proxy env vars; http_proxy in VS Code settings will not do).  Authenticated proxies are still not supported by the vsts-node-api dependency.
