### ISSUE TITLE
VSTS icon does not appear on Mac

### ISSUE THREAD

**Issue by sondreb** [Microsoft/vsts-vscode#58]
After installing the extention, the VSTS icon on the footer is not available on Mac. I have tried both stable and insider builds. Is there a command that can be triggered to show the personal access token input? "team login" only shows an error with a link to some help documentation. Have verified it works fine on Windows 10.

**Comment by jeffyoung** [comment]
Hi sondreb.  Thanks for trying out the extension!

Have you opened the root folder (or a sub-folder) of a Team Services Git repository on the Mac?  The first thing the extension tries to do is read the local repository's Git configuration, determine if it's a Team Foundation Git repository (TFS or Team Services) and, if it is, it will show the "Team" icon in the status bar and request that you log in.  "team login" is the command to use to provide your credentials, but you'll need to ensure that you have a folder/sub-folder of a Team Services repository open within VS Code?

BTW, can you let me know what the specific error message is?  If you don't have a Team Services folder open, you won't see the status bar item and the error message you _should_ see when you run "team login" (or any other command) is: "(team) No Team Services or Team Foundation Server Git repository configuration was found. Ensure you've opened a folder that contains a Git repository."

**Comment by jeffyoung** [comment]
I suspect this has to do with the keychain on the Mac.  If you're still interested in trying this out on a Mac, I'd love to get some detailed logging when you get the error.  To enable the logging, have a look [here](https://github.com/Microsoft/vsts-vscode#logging).  I'll need the information within that log file.

**Comment by TechWatching** [comment]
I have the same error on a PC for a TFVC workspace when I try to log in. When I oopen a folder of a TFS repository it does not prompt me to provide my credentials. Might be the same issue @sondreb has.

**Comment by jeffyoung** [comment]
Closing since there has been no follow-up.
