### ISSUE TITLE
Icons are duplicated

### ISSUE THREAD

**Issue by stevedenman** [Microsoft/vsts-vscode#63]
Hi, after running the extension for a while the icons are duplicated;

![2016-12-13 16_15_50-](https://cloud.githubusercontent.com/assets/8555372/21126234/d7416628-c14f-11e6-8e06-90870ed5e2c7.png)

Version 1.108.0

**Comment by jeffyoung** [comment]
Hi Steve.  Thanks for reporting this.

Could you tell me a little more about your scenario?  Are you connecting to Team Services or an on-prem TFS server?  Which OS are you using?  And about how long does it take before the issue begins to appear (once you startr VS Code)?

I've tried to repro a few times and I've run the extension for a couple of days and not seen the behavior.  So I'm gathering some data to see if I can find a pattern.

Also, if you're up for it, it'd be great if you could turn on [logging](https://github.com/Microsoft/vsts-vscode#logging) and, once the issue repros, send me the log at jeyou at microsoft dot com.  You may want to remove any PII (personally identifiable information) before sending.

If other folks run into this issue, I'd appreciate it know the same details.  Please post the information here on GitHub.

Thanks Steve.

**Comment by stevedenman** [comment]
Hi @jeffyoung, sorry about the sparse bug report - here's a little more info;
- Connecting to Team Services
- OS is Windows 10
- Not too sure how long it need to run for - not sure if it's related.

I'm not having the issue at the moment, but I'm going to keep a look out for it and will post more info / logs when possible.

**Comment by smorzhov** [comment]
Icons are duplicated after pressing ctrl+'+' or ctrl+'-'.

**Comment by jpricketMSFT** [comment]
@smorzhov - thanks for the repro steps! I was able to repro the issue. It also seems to matter how fast you hit the Ctrl+'+' or '-'. Hitting them slowly isn't a problem, but hitting quickly can add lots of status bar icons. This should allow us to fix the bug with the upcoming release.
Thanks,
Jason

**Comment by jeffyoung** [comment]
Thanks to @stevedenman and @smorzhov for helping with repros of the issue.  The PR I just submitted fixes this issue (and it's been apparent for quite a while; I just couldn't find any repro steps).  This will be in the next release which is still TBD.
