### ISSUE TITLE
TFS 2017 on premise

### ISSUE THREAD

**Issue by lawrencebr** [Microsoft/vsts-vscode#65]
We have TFS 2017 on premise and I am not able to sign in. It says I am unauthorized, to check my credentials and to try again.  I've tried multiple times, but it won't connect. I am trying to connect with the Visual Studio Team Services extension which states that it should work with TFS 2015 Update 2 and later.

**Comment by jeffyoung** [comment]
HI @lawrencebr.

I'd like to know if you could retry with some diagnostic logging enabled?  The authentication actually happens in the vsts-node-api package (which the vsts-vscode extension uses to communicate to TFS/Team Services) and I don't think there's any logging there.  However, we might get something that'll help.  If you're interested, [here's](https://github.com/Microsoft/vsts-vscode#logging) how you can enable it and get the log file I'll need.

In addition, are you attempting to access the server with HTTP or HTTPS?

**Comment by lawrencebr** [comment]
Sure, here are the logs.  I’ve removed the exact urls, but I can tell you that the urls were correct.

We only have https enabled on our TFS server.

Brad Lawrence
BYU-Idaho
Software Engineer
Kimball 250A
lawrencebr@byui.edu<mailto:lawrencebr@byui.edu>
(208) 496-7233

**Comment by jeffyoung** [comment]
Hi @lawrencebr.  It appears you must have replied to the GH email with the logs.  I didn't get the attachments in the mail but you can send them to me at jeyou at microsoft dot com.  Thanks!

**Comment by dsolodow** [comment]
Having the same issue; extension version 1.116.0, Code version 1.11.1, TFS version 2017 Update 1.
Log file attached.

[team-extension.txt](https://github.com/Microsoft/vsts-vscode/files/920432/team-extension.txt)

**Comment by dsolodow** [comment]
Still present in 1.116.1 it seems. :(

**Comment by jeffyoung** [comment]
Thanks for the log file earlier @dsolodow.  After taking a look at it, I see that you're attempting to connect to the TFS server via HTTPS.  I've been tracking that issue at #59 and should be able to have a look at it soon.

Thanks for letting me know that you're using TFS 2017 U1.  That's helpful.

**Comment by jeffyoung** [comment]
With regards to HTTPS, I just pushed a change in v1.119.0 that should help connections to on-prem servers using HTTPS.  If you're still interested, I'd be happy for you to try it out (if you haven't already).
