### ISSUE TITLE
Pinned queries: Unknown configuration setting

### ISSUE THREAD

**Issue by bgoerdt** [Microsoft/vsts-vscode#98]
The team.pinnedQueries setting does not show up in the "Team Services extension options" section of the settings menu, and the message "Unknown configuration setting" shows up in my Problems window when I add it to my user settings. The setting still works, so this is a very minor issue, but it should probably be fixed.

**Comment by jeffyoung** [comment]
Thanks for letting us know Ben.  I'll address this in an upcoming release!
